const express = require('express');
const router = express.Router();

router.use('/auth', require('./auth'));
router.use('/dashboard', require('./dashboard'));
router.use('/users', require('./users'));
router.use('/roles', require('./roles'));
router.use('/smtp-servers', require('./smtpServers'));
router.use('/sessions', require('./sessions'));
router.use('/mta-servers', require('./mtaServers'));
router.use('/domains', require('./domains'));
router.use('/data-lists', require('./dataLists'));
router.use('/smtp-groups', require('./smtpGroups'));
router.use('/offers', require('./offers'));
router.use('/affiliate-networks', require('./affiliateNetworks'));
router.use('/auto-responders', require('./autoResponders'));
router.use('/virtual-lists', require('./virtualLists'));
router.use('/production', require('./production'));
router.use('/gmail-accounts', require('./gmailAccounts'));
router.use('/gsuite-accounts', require('./gsuiteAccounts'));
router.use('/outlook-accounts', require('./outlookAccounts'));
router.use('/cloud-accounts', require('./cloudAccounts'));
router.use('/cloud-instances', require('./cloudInstances'));
router.use('/registrar-accounts', require('./registrarAccounts'));
router.use('/proxies', require('./proxies'));
router.use('/postmaster-accounts', require('./postmasterAccounts'));
router.use('/headers', require('./headers'));
router.use('/data-providers', require('./dataProviders'));
router.use('/isps', require('./isps'));
router.use('/server-providers', require('./serverProviders'));
router.use('/management-servers', require('./managementServers'));
router.use('/mailboxes', require('./mailboxes'));
router.use('/verticals', require('./verticals'));
router.use('/teams', require('./teams'));
router.use('/audit-logs', require('./auditLogs'));
router.use('/settings', require('./settings'));
router.use('/tools', require('./tools'));
router.use('/geo-manager', require('./geoManager'));
router.use('/statistics', require('./statistics'));
router.use('/pmta', require('./pmta'));

module.exports = router;
